# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.9"
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running tests..."
      - mkdir -p reports
      - python -m pytest test_app.py -v --junitxml=reports/junit.xml

  build:
    commands:
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "✅ All tests passed. Build successful!"

artifacts:
  files:
    - '**/*'
  base-directory: '.'

reports:
  pytest-reports:
    files:
      - '**/*'
    base-directory: 'reports'
    discard-paths: no
